# Generated by Django 5.2.7 on 2025-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='00000', max_length=255),
        ),
    ]
