# Generated by Django 5.2.7 on 2025-10-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_first_n_8f83e0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_first_n_8f83e0_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
